### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by rei-01-18** [rei-01-18/furima-35094#9]
自身のフリマアプリのURL.  https://furima-35094.herokuapp.com/

Basic認証のIDとパスワード   admin.   2222

出品者用のメールアドレスとパスワード   bbb@bb.         222bbb

購入者用のメールアドレスとパスワード.  ccc@cc.          333ccc

**Comment by snkw-works** [comment]
@rei-01-18 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [x] **issueに記載されたHerokuのURLにアクセスし、同じくissueに記載されたIDとパスワードを入力すると、最終課題アプリ（FURIMA）が表示されるよう修正しましょう**
現状、basic認証が実装されていないため、IDとパスワードを入力しなくてもアプリが表示できてしまう状態です。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by mo1015** [comment]
ご提出ありがとうございます！
問題なく正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/62644781/114523061-e8c57880-9c7e-11eb-8b92-d9e6e5f3ec2d.png)
